export const formConditionalFields = [
  { key: "allergies", details: "allergiesDetails" },
  { key: "currentMedications", details: "medicationsDetails" },
  { key: "existingConditions", details: "conditionsDetails" },
  { key: "previousSurgeries", details: "surgeriesDetails" },
  { key: "heartDisease", details: "heartDiseaseDetails" },
  { key: "kidneyDisease", details: "kidneyDiseaseDetails" },
  { key: "liverDisease", details: "liverDiseaseDetails" },
  { key: "autoimmuneDisorders", details: "autoimmuneDisordersDetails" },
  { key: "otherConditions", details: "otherConditionsDetails" },
  { key: "recentHealthChanges", details: "healthChangesDetails" },
  { key: "injectablesConcerns", details: "injectablesConcernsDetails" },
  { key: "needleFear", details: "needleConcernsDetails" },
];
export const formFields = [
  "firstName",
  "lastName",
  "streetAddress",
  "email",
  "phoneNumber",
  "preferredContact",
  "allergies",
  "currentMedications",
  "existingConditions",
  "previousSurgeries",
  "heartDisease",
  "kidneyDisease",
  "liverDisease",
  "autoimmuneDisorders",
  "otherConditions",
  "lastCheckupDate",
  "recentHealthChanges",
  "injectablesConcerns",
  "needleFear",
  "familyMedicalHistory",
  "additionalInfo",
  "consentAgreement",
  "consentSharing"
];
